name: Deploy Firebase Functions
on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: ./functions

      - name: Create Environment Variables
        run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
        working-directory: ./functions

      - name: Authenticate and Deploy to Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/service-account.json"
          npx firebase-tools deploy --only functions --project cohi-survey-engine
